name: Generate Artifacts

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout main branch
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      # 2. Setup Python 3.x
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 3. Get Python version for cache key
      - name: Get Python version
        id: python-version
        run: echo "version=$(python3 -c 'import sys; print(f\"{sys.version_info.major}.{sys.version_info.minor}\")')" >> $GITHUB_OUTPUT

      # 4. Cache the entire venv
      - name: Cache venv
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: /tmp/venv
          key: ${{ runner.os }}-venv-py${{ steps.python-version.outputs.version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-py${{ steps.python-version.outputs.version }}-

      # 5. Set up venv if cache missed
      - name: Set up venv
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python3 -m venv /tmp/venv
          /tmp/venv/bin/pip install --upgrade pip
          /tmp/venv/bin/pip install -r requirements.txt

      # 6. Add venv to PATH globally for all steps
      - name: Add venv to PATH
        run: echo "/tmp/venv/bin" >> $GITHUB_PATH

      # 7. Switch to autogen-artifacts branch (fresh history)
      - name: Switch to autogen-artifacts branch
        run: |
          git fetch origin
          if git ls-remote --exit-code --heads origin autogen-artifacts; then
            git checkout --orphan autogen-artifacts
          else
            git checkout --orphan autogen-artifacts
          fi
          git reset --hard
          git clean -fdx

      # 8. Copy scripts (from main) into branch
      - name: Copy scripts
        run: |
          cp -r adaway skynet requirements.txt ./

      # 9. Restore CSV if exists
      - name: Restore CSV files
        run: |
          mkdir -p adaway skynet
          if [ -f skynet/ip_counts_history.csv ]; then
            cp skynet/ip_counts_history.csv skynet/
          fi
          if [ -f adaway/counts_history.csv ]; then
            cp adaway/counts_history.csv adaway/
          fi

      # 10. Run adaway scripts
      - name: Run adaway main.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        working-directory: adaway
        run: python3 main.py

      - name: Run adaway plot.py
        working-directory: adaway
        run: python3 plot.py

      # 11. Run skynet scripts
      - name: Run skynet update.sh
        working-directory: skynet
        run: bash update.sh

      - name: Run skynet plot.py
        working-directory: skynet
        run: python3 plot.py

      # 12. Commit and push all generated files (including ignored)
      - name: Commit and push autogen-artifacts
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -f adaway/unified_hosts.txt
          git add -f adaway/counts_history.png
          git add -f adaway/counts_graph.png
          git add -f skynet/ip_counts_history.csv
          git add -f skynet/ip_counts_graph.png
          git add .
          git commit -m "Update generated hosts and filter files" || echo "No changes to commit"
          git push origin autogen-artifacts --force
