name: Generate Artifacts

on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout main branch
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      # 2. Set up Python virtual environment
      - name: Set up venv
        run: python3 -m venv .venv

      # 3. Cache virtual environment
      - name: Cache venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      # 4. Upgrade pip and install dependencies in venv
      - name: Install dependencies
        run: |
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Backup scripts before branch switch
      - name: Backup scripts
        run: |
          mkdir -p /tmp/scripts
          cp -r adaway /tmp/scripts/
          cp -r skynet /tmp/scripts/
          cp requirements.txt /tmp/scripts/

      # 6. Switch to autogen-artifacts branch
      - name: Switch to autogen-artifacts branch
        run: |
          git fetch origin
          if git ls-remote --exit-code --heads origin autogen-artifacts; then
            git checkout autogen-artifacts
          else
            git checkout --orphan autogen-artifacts
          fi

      # 7. Backup CSV files
      - name: Backup CSV
        run: |
          mkdir -p /tmp/backup
          cp skynet/ip_counts_history.csv /tmp/backup/ 2>/dev/null || true
          cp adaway/counts_history.csv /tmp/backup/ 2>/dev/null || true

      # 8. Clean branch except .git
      - name: Clean branch
        run: |
          find . -mindepth 1 ! -path './.git*' -delete

      # 9. Restore scripts from main branch backup
      - name: Restore scripts
        run: cp -r /tmp/scripts/* ./

      # 10. Restore CSV
      - name: Restore CSV
        run: |
          mkdir -p adaway skynet
          cp /tmp/backup/ip_counts_history.csv skynet/ 2>/dev/null || true
          cp /tmp/backup/counts_history.csv adaway/ 2>/dev/null || true

      # 11. Run adaway scripts
      - name: Run main.py script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        working-directory: adaway
        run: |
          source ../.venv/bin/activate
          python3 main.py

      - name: Run plot.py script
        working-directory: adaway
        run: |
          source ../.venv/bin/activate
          python3 plot.py

      # 12. Run skynet scripts
      - name: Run bash update.sh
        working-directory: skynet
        run: bash update.sh

      - name: Run plot.py script
        working-directory: skynet
        run: |
          source ../.venv/bin/activate
          python3 plot.py

      # 13. Commit and push changes
      - name: Commit and push autogen-artifacts files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update hosts and filter files" || echo "No changes to commit"
          git push origin autogen-artifacts --force
