name: Generate Artifacts

on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout main branch (scripts live here)
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      # Cache pip dependencies
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      # 2. Save scripts somewhere safe before branch switch
      - name: Backup scripts
        run: |
          mkdir -p /tmp/scripts
          cp -r adaway /tmp/scripts/
          cp -r skynet /tmp/scripts/
          cp requirements.txt /tmp/scripts/

      # 3. Switch/create autogen-artifacts branch
      - name: Switch to autogen-artifacts branch
        run: |
          git fetch origin
          if git ls-remote --exit-code --heads origin autogen-artifacts; then
            git checkout autogen-artifacts
          else
            git checkout --orphan autogen-artifacts
          fi

      # 4. Backup CSV before cleaning
      - name: Backup CSV
        run: |
          mkdir -p /tmp/backup
          cp skynet/ip_counts_history.csv /tmp/backup/ 2>/dev/null || true
          cp adaway/counts_history.csv /tmp/backup/ 2>/dev/null || true

      # 5. Clean branch but keep .git
      - name: Clean branch
        run: |
          find . -mindepth 1 ! -path './.git*' -delete

      # 6. Restore scripts from main branch backup
      - name: Restore scripts
        run: |
          cp -r /tmp/scripts/* ./

      # 7. Restore CSV
      - name: Restore CSV
        run: |
          mkdir -p adaway skynet
          cp /tmp/backup/ip_counts_history.csv skynet/ 2>/dev/null || true
          cp /tmp/backup/counts_history.csv adaway/ 2>/dev/null || true

      # 8. Run adaway scripts
      - name: Run main.py script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        working-directory: adaway
        run: python3 main.py

      - name: Run adaway plot.py script
        working-directory: adaway
        run: python3 plot.py

      # 9. Run skynet scripts
      - name: Run skynet bash script
        working-directory: skynet
        run: bash update.sh

      - name: Run skynet plot.py script
        working-directory: skynet
        run: python3 plot.py

      # 10. Commit and push changes
      - name: Commit and push autogen-artifacts files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update hosts and filter files" || echo "No changes to commit"
          git push origin autogen-artifacts --force
